// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqnfnerxdzyodxxihyku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbmZuZXJ4ZHp5b2R4eGloeWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODM0MjgsImV4cCI6MjA2NDA1OTQyOH0.s6xm_uacCojkMdloEv8PFL6t__GQuD407CnCHMFR-uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);