// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecmyhluumtrycmprnkkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjbXlobHV1bXRyeWNtcHJua2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzAyMTgsImV4cCI6MjA2NDkwNjIxOH0.QAtt_4dlvJqVdfrPjkdUrKguC2IZmb1S49X0TfLAMhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);